name: Build Angular app and deploy to GitHub pages

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:

    - uses: actions/checkout@v4
      # https://github.com/marketplace/actions/checkout
    
    - name: Use Node.js ${{ matrix.node-version }}
      # https://github.com/marketplace/actions/setup-node-js-environment
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - run: npm install

    - uses: actions/checkout@v4
      # https://github.com/marketplace/actions/checkout
      with:
        ref: pages
        path: gh-pages/

    - run: find gh-pages/ -type f

    - run: npm run build -- --output-path dist
    
    - run: find dist/browser -type f

    - run: rm $(git ls-files)
      working-directory: gh-pages

    - run: cp -rP dist/browser/ gh-pages/

    - run: git status
      working-directory: gh-pages
      
    - run: git add --all
      working-directory: gh-pages

    - run: git commit -m "$GITHUB_ACTION $(date '+%Y-%m-%d %H:%M:%S')\n$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
      working-directory: gh-pages

    - run: git status
      working-directory: gh-pages
      
    - run: git push
      working-directory: gh-pages
