name: Build Angular app and deploy to GitHub pages

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:

    - name: Use Node.js ${{ matrix.node-version }}
      # https://github.com/marketplace/actions/setup-node-js-environment
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - uses: actions/checkout@v4
      # https://github.com/marketplace/actions/checkout
    
    - run: find static-pages -type f

    - run: npm install

    - uses: actions/checkout@v4
      # https://github.com/marketplace/actions/checkout
      with:
        ref: pages
        path: static-pages/browser

    - run: find static-pages -type f

    - run: npm run build -- --output-path static-pages
    
    - run: find static-pages -type f
